---
#Verbose: true
verbose: true
output: # Path to a log file, if not set, write to stdout
listen-addrs: 
  - "127.0.0.1" # Server listen address
listen-ports: 
  - 53 # Listening ports. Zero value disables TCP and UDP listeners
#https-port: # Listening ports for DNS-over-HTTPS
#tls-port: [] # Listening ports for DNS-over-TLS
#quic-port: [] # Listening ports for DNS-over-QUIC
#dnscrypt-port: [] # Listening ports for DNSCrypt
# Encryption config
# --
#tls-crt: # Path to the .crt/.pem with the certificate chain, when the proxy is used as a DNS server
#tls-key: # Path to a file with the private key, when the proxy is used as a DNS server
#tls-min-version: # Minimum TLS version, for example 1.0
#tls-max-version = # Maximum TLS version, for example 1.3
insecure: false # Disable secure TLS certificate validation, for DNS server
#dnscrypt-config = "" # Path to a file with DNSCrypt configuration. You can generate one using https://github.com/ameshkov/dnscrypt

#Upstream DNS servers settings
#--
#Upstreams = ["https://dns.plido.net/dns-query"] # An upstream to be used (can be specified multiple times). You can also specify path to a file with the list of servers, it must be set
upstream: 
  - 1.1.1.1:53
bootstrap: 
  - 8.8.8.8:53 # Bootstrap DNS for DoH and DoT, can be specified multiple times 
#fallback: [] # Fallback DNS resolver to use when regular ones are unavailable, can be specified multiple times. You can also specify path to a file with the list of servers"`
#allservers = false # If true, parallel queries to all configured upstream servers
#fastest-addr = # Respond to A or AAAA requests only with the fastest IP address, detected by ICMP response time or TCP connection time

# Cache settings
# --
#cache: true # If true, DNS cache is enabled
cache-size: 64000 # Cache size value, default: 64k
#cache-min-ttl: # Minimum TTL value for DNS entries, in seconds. Capped at 3600. Artificially extending TTLs should only be done with careful consideration."`
#cache-max-ttl: # Maximum TTL value for DNS entries, in seconds
#cache-optimistic: # CacheOptimistic, if set to true, enables the optimistic DNS cache. That means that cached results will be served even if their cache TTL has already expired

# Anti-DNS amplification measures
# --
ratelimit: 0 # Ratelimit (requests per second)
#refuse-any = false # If true, refuse ANY requests

# ECS settings
# --
#EnableEDNSSubnet = true # Use EDNS Client Subnet extension
#edns = true # Send EDNS custom client address
#edns-addr= 

#DNS64 settings
# --
#dns64: true # If specified, dnsproxy will act as a DNS64 server
#dns64-prefix = "" # If specified, this is the DNS64 prefix dnsproxy will be using when it works as a DNS64 server. If not specified, dnsproxy uses the 'Well-Known Prefix' 64:ff9b::

#Other settings and options
#--

ipv6-disabled: false # If true, all AAAA requests will be replied with NoError RCode and empty answer
# bogus-nxdomain = [""] # Transform responses that contain at least one of the given IP addresses into NXDOMAIN. Can be specified multiple times
udp-buf-size: 0 # Set the size of the UDP buffer in bytes. A value <= 0 will use the system default.
max-go-routines: 0 # Set the maximum number of go routines. A value <= 0 will not not set a maximum default to 0
version: false # Prints the program version"`